### ISSUE TITLE
Early Execution of Proposal

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#12]
Suppose that only one vote is required to reach the overall minimum criteria based on the proposal type, there would be an option for the last voter to execute actions.

**Comment by averybui** [comment]
The last voter will have two choices: vote only or vote and execute. If they choose to execute, they will have to pay for both transactions. Although the gas fee is insignificant, this may seem unfair.

Suggestions:

1. Admin should automatically pay for the proposal execute gas fee. Once the last voter votes on a proposal, the executed action transaction will be sent to the admin. The admin can:
- either pay in bulk for all the early execution proposals. 
- the early execution proposals should have a tag that will be automatically approved to be paid with the admin wallet.
2. Open a small vault specifically for paying the execution gas fee. Anyone who votes and executes will have the execute gas fee deducted from this vault.

**Comment by SJPxdc** [comment]
> Suppose that only one vote is required to reach the overall minimum criteria based on the proposal type, there would be an option for the last voter to execute actions.

Can you provide an example?

**Comment by SupersnipsXDC** [comment]
In my opinion, Grants shouldn't be able to execute before the given voting deadline. It should only be possible for technical or other proposals.  Grants should be paid out / executed the moment the actual voting period ends. Let me know your thoughts. It could also be done to let them execute before but would like to hear other thoughts on this.

**Comment by 0xbeny** [comment]
As we discussed, it does make sense to have the Early Execution feature under these conditions:
- The proposer can specify whether early execution or not. meanwhile creating proposals.
- Since only the proposals that reach requirements can be executed and _No matter who can execute that #18_  ,
We can have a separate discussion in a new thread about Automatic #22
