### ISSUE TITLE
Slashing mechanism for voters?

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#16]

**Comment by SJPxdc** [comment]
Please provide a written description of the slashing mechanism purpose and procedure.

**Comment by SupersnipsXDC** [comment]
just to kick off discussion: For Peoples House there should be possibility to slash i.e not earn any more rewards if Voter is inactive for 1 or 2 full voting period/s.

**Comment by SeanXDCAustralia** [comment]
Lets please use a different term than "slashing" .. just to put some space and distance in the relation to validating Masternodes.

**Comment by 0xbeny** [comment]
No conclusion yet on this topic. We'll reopen it after DAOFIN launch based on Governance decision on how we want it implement it.
