### ISSUE TITLE
Is there any criteria to create a proposal?

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#2]
**Intro:**

Apart from managing Committees, To get ball rolling on DAOFIN, we need to open the floor to proposers and community members to create a proposal. There is one thing to note here is that based on the current [draft](https://www.xdc.dev/riteshkakkad/daofin-draft-decentralizing-xdcs-ecosystem-development-1da), anyone can create a proposal. so there might be a risk of spam proposals to over come this problem there are a couple of fixes:

1. Proposers must create 1 proposal inside 1 block (1 proposal = 1 block)
2. Proposers must have enough XDC balance while calling `createProposal` function from smart contract
3. Validating the content of proposal by a list of addresses like Judiciary committee or an admin

**Comment by WalterBlueu** [comment]
I'd propose a slight modification to #2, have the proposer stake their XDC while the proposal is live.  This would open a door for the judiciary committee to punish proposers who were bad actors by burning their stake.  This would be one mechanism to keep the bar to creating a proposal low while still being able to deter bad actors.

**Comment by 0xbeny** [comment]
Super! thanks for your collaboration.

I think that would be a strong mechanism to prevent spam proposal. in the above scenario, Is the stake amount will refund to proposer after sometime or it's like cost of creating proposal?

**Comment by 0xbeny** [comment]
**A suggestion:** During the proposal creation, we charge extra XDC tokens(native token) and send it to DAO treasury as proposal fee and it's not refundable. example: Daofin charges a fixed amount like `1,000 XDC` per proposal regardless of who is sending it.

**Comment by 0xbeny** [comment]
The agreed scenario is charging the proposer X amount of XDC token which is not refundable.
