### ISSUE TITLE
DAOFIN: High Level Architecture

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#3]
The image below demonstrated the high-level architecture of DAOFIN.
DAOFIN is built on top of [Aragon OSX protocol](https://aragon.org/) as a plugin.

You can find the Daofin Plugin, SDK, Subgraph here is this repo: [Link](https://github.com/XinFinOrg/osx-daofin)
and Frontend is [here](https://github.com/XinFinOrg/daofin-ui)

<img width="737" alt="Screenshot 2023-10-12 at 9 56 23 AM" src="https://github.com/XinFinOrg/osx-daofin/assets/55846654/aa27b426-be80-47a8-990a-f40c21dff7dc">

**Comment by WalterBlueu** [comment]
How is the DAO Treasury secured?  Do transactions out of the treasury require multiple signers, or multiple signers on a triggering action that causes funds to leave the treasury?  Are those signers the Judiciary committee?

**Comment by 0xbeny** [comment]
Good Point!

Treasury is managed by permissions. it means that anyone(either EOA or SC) with the right permission can execute some sort of actions(actions would be anything).

For instance, **only** Daofin Plugin Smart contract has a right permission on Treasury. the only interaction with treasury is where we sum up the votes on a proposal and if it meets the criteria, now it's time to execute actions. e.g. releasing X amount grant from Treasury, etc

There is no direct interaction with treasury except sending assets to Treasury. in other words, sending assets it's just a transaction without needs of any permissions. however, releasing or withdrawing assets must require permissions and right governance to be more fair and secure.


In general, It's fully customizable on how we interact with Treasury.

I'd strongly suggest to read this [article](https://blog.aragon.org/what-is-a-dao/), since, DAOFIN is built on top of the Aragon OSX protocol.


Just let me know, if there is any concerns. :)
