### ISSUE TITLE
Types of Proposal

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#9]
Along with general purpose proposals which is going to be submitted around the ecosystem growth(grants, core protocol,..), there would be other types of decisions that DAOFIN needs to operate and stay alive:

1- **Grant, decision making, etc**

2- **Voting Settings Proposal**:  any changes on Quorum and Threshold per each committee.

3- **Punishing a spam proposal by the committees** : As there is a discussion on #2 , we need a mechanism to punish a bad proposer. so in this case, we need to a proper function on DAO to apply the punishment. This can be form as a proposal.

4- **Judiciaries Replacement**: As discussed on #1 , same as 2nd option, it should be form as a proposal.

5- **Specifying a new Election period**

**Comment by 0xbeny** [comment]
Do the criteria of each types of proposals can be different? in other words, Do the quorum and pass rate may varies per proposal type?

**Comment by SeanXDCAustralia** [comment]
> Do the criteria of each types of proposals can be different? in other words, Do the quorum and pass rate may varies per proposal type?
I am open to this suggestion. IF I need to formalise my support, just let me know!

**Comment by 0xbeny** [comment]
As discussed, each proposal type has different configurations per committee. this simply means that minimum criteria vary from proposal to proposal.

**Comment by 0xbeny** [comment]
Also, we could enhance the functionalities by applying `ProposalType`, we(DAO Treasury) can include or exclude one committee in minimum and two committees in maximum.

Example: ProposalType `X`, only receives votes from Judiciaries and People. not Master Node senate.

This makes DAOFIN more dynamic, there is no code change by devs. the only need is to create a new `ProposalType`.
All changes happen by committees.

**Downside:** When we delegate this decision to the community. that would be difficult to agree on and takes time. so which means that it's out of control since no single party can decide.

**Comment by 0xbeny** [comment]
Proposal Types Agreed by the community. open a new issue if you want to propose a new proposal type.
